import type { ControlDefinition, Severity } from '@launchproof/contracts';

const controls: Array<[string, string, ControlDefinition['domain'], string, number, Severity]> = [
  [
    'LP-01',
    'Input Boundaries',
    'security',
    'Untrusted input is validated at trust boundaries.',
    5,
    'high',
  ],
  [
    'LP-02',
    'Authentication',
    'security',
    'Protected functionality establishes user identity.',
    6,
    'critical',
  ],
  [
    'LP-03',
    'Authorization',
    'security',
    'Sensitive operations enforce authorization.',
    8,
    'critical',
  ],
  [
    'LP-04',
    'Tenant Isolation',
    'security',
    'Tenant-scoped systems constrain cross-tenant access.',
    9,
    'critical',
  ],
  [
    'LP-05',
    'Least Privilege',
    'security',
    'Privileges are limited to the minimum required.',
    4,
    'high',
  ],
  [
    'LP-06',
    'Secrets',
    'security',
    'Secrets are not committed or exposed to untrusted clients.',
    8,
    'critical',
  ],
  [
    'LP-07',
    'Safe Data Access',
    'security',
    'Data access uses safe parameterization and scoped repositories.',
    6,
    'high',
  ],
  [
    'LP-08',
    'Dependency Integrity',
    'security',
    'Dependencies and lockfiles support reproducible integrity review.',
    5,
    'high',
  ],
  [
    'LP-09',
    'Error Safety',
    'quality',
    'Errors avoid unsafe disclosure and fail predictably.',
    3,
    'medium',
  ],
  ['LP-10', 'Auditability', 'production', 'Security-relevant actions can be traced.', 4, 'medium'],
  [
    'LP-11',
    'Abuse Resistance',
    'security',
    'Public or expensive operations include abuse controls.',
    5,
    'high',
  ],
  [
    'LP-12',
    'Testable Guarantees',
    'testing',
    'Important guarantees have executable test evidence.',
    7,
    'high',
  ],
  [
    'LP-13',
    'Production Configuration',
    'production',
    'Production configuration is explicit and safe.',
    5,
    'high',
  ],
  [
    'LP-14',
    'Observability',
    'production',
    'Production behavior can be observed without leaking secrets.',
    3,
    'medium',
  ],
  [
    'LP-15',
    'Accessibility',
    'accessibility',
    'User-facing functionality has accessibility evidence.',
    3,
    'medium',
  ],
  [
    'LP-16',
    'Release Provenance',
    'production',
    'Release evidence identifies repository, commit, policy and analyzer versions.',
    5,
    'high',
  ],
  [
    'LP-17',
    'Evidence-Backed Claims',
    'architecture',
    'Assurance claims reference structured evidence.',
    6,
    'high',
  ],
  [
    'LP-18',
    'AI Distrust',
    'security',
    'AI output cannot independently pass controls or gates.',
    6,
    'critical',
  ],
  [
    'LP-19',
    'Secure AI Integration',
    'security',
    'AI providers obey explicit data-governance and credential boundaries.',
    4,
    'high',
  ],
  [
    'LP-20',
    'Fail Safely',
    'security',
    'Unknown or invalid assurance state never silently becomes passed.',
    7,
    'critical',
  ],
];

export const BUILD_STANDARD_VERSION = '0.1';
export const buildStandard: ControlDefinition[] = controls.map(
  ([id, title, domain, description, weight, severityOnFailure]) => ({
    id,
    title,
    domain,
    description,
    version: BUILD_STANDARD_VERSION,
    weight,
    severityOnFailure,
  }),
);
export function getControl(id: string): ControlDefinition {
  const control = buildStandard.find((item) => item.id === id);
  if (!control) throw new Error(`Unknown LaunchProof control ${id}`);
  return control;
}
